run:
  timeout: 5m
  exclude-dirs:
    - docs

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive

linters-settings:
  errcheck:
    check-type-assertions: true