// Package product provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package product

// CreateProductRequest defines model for CreateProductRequest.
type CreateProductRequest struct {
	Category    string  `json:"category"`
	Description string  `json:"description"`
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Stock       int32   `json:"stock"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error  string                  `json:"error"`
	Fields *map[string]interface{} `json:"fields,omitempty"`
}

// Product defines model for Product.
type Product struct {
	Category    string  `json:"category"`
	Description string  `json:"description"`
	Id          int64   `json:"id"`
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Stock       int32   `json:"stock"`
}

// ProductsCreateJSONRequestBody defines body for ProductsCreate for application/json ContentType.
type ProductsCreateJSONRequestBody = CreateProductRequest
